PRODUCT_ID := a7ns
CLASS_ID:=iptime
BCM5357C0_SUPPORT:=y
NVRAM_FILENAME:=nvram.txt
BOOT_FILE:=cfez.bin.470x.6.37.14.62
MAX_FIRMWARE_SIZE:=0xf90000
KERNEL_POSTFIX:=fsrc
TNTFS_MODULE_NAME:=tntfs.ko.fsrc

LANG_PACKS:=kr,en
